ARG_LABELS = {
    "--wallet": "Wallet File",
    "--wallet-type": "Wallet Type",
    "--mpk": "Master Public Key",
    "--addrs": "Addresses",
    "--addressdb": "Address Database",
    "--addr-limit": "Address Limit",
    "--addr-start-index": "Start Index",
    "--typos": "Typos Allowed",
    "--big-typos": "Big Typos",
    "--min-typos": "Minimum Typos",
    "--close-match": "Close Match Threshold",
    "--passphrase": "Use Passphrase",
    "--passphrase-arg": "Passphrase Value(s)",
    "--passphrase-list": "Passphrase File",
    "--passphrase-prompt": "Prompt for Passphrase",
    "--mnemonic": "Mnemonic",
    "--mnemonic-prompt": "Prompt for Mnemonic",
    "--mnemonic-length": "Mnemonic Length",
    "--language": "Language",
    "--bip32-path": "BIP32 Path",
    "--substrate-path": "Substrate Path",
    "--checksinglexpubaddress": "Check Single XPUB Address",
    "--force-p2sh": "Force P2SH",
    "--force-p2tr": "Force P2TR",
    "--pathlist": "Path List File",
    "--transform-wordswaps": "Transform Word Swaps",
    "--skip": "Skip",
    "--threads": "Threads",
    "--worker": "Worker ID",
    "--max-eta": "Max ETA",
    "--no-eta": "Suppress ETA",
    "--no-dupchecks": "Disable Duplicate Checking",
    "--no-progress": "Disable Progress Display",
    "--no-pause": "Disable Pause Prompt",
    "--no-gui": "No GUI Mode",
    "--performance": "Enable Performance Mode",
    "--version": "Show Version",
    "--disablesecuritywarnings": "Disable Security Warnings",
    "--tokenlist": "Wordlist File",
    "--keep-tokens-order": "Keep Wordlist Order",
    "--max-tokens": "Max Tokens",
    "--min-tokens": "Min Tokens",
    "--seedlist": "Seed List File",
    "--multi-file-seedlist": "Multi-file Seedlist",
    "--listseeds": "List Seeds",
    "--savevalidseeds": "Save Valid Seeds",
    "--savevalidseeds-filesize": "Seed File Size Limit",
    "--skip-worker-checksum": "Skip Worker Checksum",
    "--enable-opencl": "Enable OpenCL",
    "--opencl-workgroup-size": "OpenCL Workgroup Size",
    "--opencl-platform": "OpenCL Platform",
    "--opencl-devices": "OpenCL Devices",
    "--opencl-info": "Show OpenCL Info",
    "--force-checksum-in-generator": "Force Checksum Generator",
    "--dsw": "Allow Word Swaps"
}
